name: CI Pipeline for Messaging App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: instant_comm
          MYSQL_USER: user
          MYSQL_PASSWORD: userpassword
        ports:
          - 3306:3306

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run Docker Compose
      uses: sudo-bot/action-docker-compose@latest
      with:
        cli-args: "up -d --build"

    - name: Wait for MySQL to be Ready
      run: |
        until docker exec mysql mysqladmin ping -h "127.0.0.1" --silent; do
          echo "Waiting for database connection..."
          sleep 5
        done

    - name: Log in to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo $HEROKU_API_KEY | heroku auth:token

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku git:remote -a test_app
        git push heroku main

    - name: Tear Down Docker Compose
      uses: sudo-bot/action-docker-compose@latest
      with:
        cli-args: "down"
